# Generated by Django 3.2 on 2021-04-28 08:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.unique_code, max_length=10, unique=True),
        ),
    ]
