# Generated by Django 3.2 on 2021-05-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210428_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_can_add',
        ),
    ]
